# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

JavascriptTesting::Application.load_tasks

desc 'Run JavaScript unit tests'
task :javascript_test do
  fail "npm test failure" unless system("npm test")
end

task :test => ["javascript_test"]
